# Generated by Django 3.2.5 on 2021-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.TextField()),
                ('category', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'fin_reports',
            },
        ),
    ]
