# Generated by Django 3.2.9 on 2021-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'fin_reports',
            },
        ),
    ]
