# Generated by Django 3.2.9 on 2021-11-23 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finreports',
            name='price',
            field=models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
