# Generated by Django 3.2.5 on 2021-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jejuschedule',
            name='reg_date',
            field=models.DateTimeField(),
        ),
    ]
