# Generated by Django 3.2.5 on 2021-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField()),
                ('voucher', models.TextField()),
                ('caution', models.TextField()),
                ('fees', models.IntegerField()),
                ('client', models.TextField()),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
