# Generated by Django 3.2.5 on 2021-12-31 02:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('re_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_date', models.DateField()),
                ('user', models.IntegerField()),
                ('day', models.IntegerField()),
                ('people', models.IntegerField()),
                ('plane', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
                ('acc', models.IntegerField()),
                ('activity', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
            ],
            options={
                'db_table': 'pay',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('people', models.IntegerField()),
                ('day', models.IntegerField()),
                ('plane_unit', models.IntegerField()),
                ('plane_price', models.IntegerField()),
                ('acc_unit', models.IntegerField()),
                ('acc_price', models.IntegerField()),
                ('act_unit', models.IntegerField()),
                ('act_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('jeju_schedule', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
