# Generated by Django 3.2.5 on 2021-12-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
    ]
