# Generated by Django 3.2.9 on 2021-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brevity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('plane', models.IntegerField()),
                ('accommodation', models.IntegerField()),
                ('activity', models.IntegerField(null=True)),
                ('restaurant', models.TextField(null=True)),
                ('shop', models.TextField(null=True)),
                ('tourism', models.TextField(null=True)),
                ('olle', models.TextField(null=True)),
                ('option', models.TextField()),
            ],
            options={
                'db_table': 'brevity',
            },
        ),
    ]
