# Generated by Django 3.2.5 on 2021-12-16 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jejuschedule',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 33, 8, 255885)),
        ),
    ]
